"""Download the checkpoint's exact Google Fonts request into assets/fonts/ and write
src/styles/fonts.css pointing at the local files. Same files, same metrics, same
unicode-range subsets as the checkpoint, but no network needed at demo time.

Usage: python -I scripts/fetch_fonts.py
"""
import os, re, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CSS = ('https://fonts.googleapis.com/css2?family=Anton+SC&family=Barlow:wght@400;500;600;700'
       '&family=JetBrains+Mono:wght@500&family=Poppins:wght@400;500;600;700;800&display=swap')
# A current Chrome UA, so Google serves woff2 with unicode-range subsets (what Chrome got in the checkpoint).
UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0.0.0 Safari/537.36'


def get(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': UA})).read()


css = get(CSS).decode()
os.makedirs(os.path.join(ROOT, 'assets', 'fonts'), exist_ok=True)


def local(m):
    url = m.group(1)
    name = url.split('/s/')[1].replace('/', '-')  # e.g. poppins-v24-pxiByp8k....woff2
    with open(os.path.join(ROOT, 'assets', 'fonts', name), 'wb') as f:
        f.write(get(url))
    return 'url(../../assets/fonts/%s)' % name


css = re.sub(r'url\((https://fonts\.gstatic\.com/[^)]+)\)', local, css)
with open(os.path.join(ROOT, 'src', 'styles', 'fonts.css'), 'w') as f:
    f.write('/* Generated by scripts/fetch_fonts.py from the checkpoint\'s Google Fonts URL. Don\'t edit. */\n' + css)
print(len(re.findall('@font-face', css)), 'faces,', len(os.listdir(os.path.join(ROOT, 'assets', 'fonts'))), 'files')
